### ISSUE TITLE
Text formatting breaks when editing from Properties > Content 

### ISSUE THREAD

**Issue by nish7x** [frappe/builder#21] opened 2023-10-30 16:09 UTC
When editing this text from Content field in Properties panel: 

<img width="1131" alt="image" src="https://github.com/frappe/builder/assets/8917840/20e9004c-15f3-4af1-97dc-170e50ad5f3a">

The font style is reset, as below: 

<img width="1069" alt="image" src="https://github.com/frappe/builder/assets/8917840/7fed2430-8017-458f-aec9-9de7a6d7fbf4">

**Comment by surajshetty3416** [comment] 2023-10-31 06:46
The font-family might be set in the text and not on the block which is why the new content takes parent's font-family (which is difference).

Recommend you to set font-family in the block itself.

(closing this as it is not a bug, but will look into the way to fix the UX)

**Closed by surajshetty3416** 2023-10-31 06:46 UTC
Labels: bug
